[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Troy Neubauer <troyneubauer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "day1a"
path = "src/day1/a/main.rs"


[dependencies]
